In [2]:
import pandas as pd
import numpy as np

In [4]:
dataset = pd.read_excel(
	"./data/Средние_потребительские_цены_на_продовольственные_товарыСредние.xlsx", 
	sheet_name="Средние потребительские цены на"
)
dataset.head(10)

d:\programming\AI\ai_env\lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,Средние потребительские цены на продовольственные товары,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 85,Unnamed: 86,Unnamed: 87,Unnamed: 88,Unnamed: 89,Unnamed: 90,Unnamed: 91,Unnamed: 92,Unnamed: 93,Unnamed: 94
0,Страна,Федеральный округ,Субъект РФ,Год,Месяц,Дата,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Российская Федерация,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,,Центральный федеральный округ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,,,Белгородская область,Брянская область,Владимирская область,Воронежская область,Ивановская область,Калужская область,Костромская область,...,Республика Саха (Якутия),Забайкальский край,Камчатский край,Приморский край,Хабаровский край,Амурская область,Магаданская область,Сахалинская область,Еврейская автономная область,Чукотский автономный округ
4,NaN,2022,2022,2022,2022,2022,2022,2022,2022,2022,...,2022,2022,2022,2022,2022,2022,2022,2022,2022,2022
5,NaN,Июль,Июль,Июль,Июль,Июль,Июль,Июль,Июль,Июль,...,Июль,Июль,Июль,Июль,Июль,Июль,Июль,Июль,Июль,Июль
6,Товар или услуга,08.07.2022,08.07.2022,08.07.2022,08.07.2022,08.07.2022,08.07.2022,08.07.2022,08.07.2022,08.07.2022,...,08.07.2022,08.07.2022,08.07.2022,08.07.2022,08.07.2022,08.07.2022,08.07.2022,08.07.2022,08.07.2022,08.07.2022
7,"Маргарин, кг",246.43,266.12,221.7,273.63,260.92,211.41,272.81,228.31,269.03,...,332.93,231.06,373.65,312.25,317.27,238,249.93,393.55,275.56,309.82
8,"Сметана, кг",283.99,307.03,220.87,248.52,294.6,274.12,322.54,296.56,300.24,...,422.16,408.28,583.24,335.4,347.32,284.49,594.95,484.68,369.41,746.86
9,"Говядина (кроме бескостного мяса), кг",474.7,552.69,413.69,539.1,503.18,453.39,459.32,564.69,482.46,...,565.06,429.42,733.3,506.11,551.65,474.4,695.17,585.27,519.53,788.69

In [7]:
def row_stringify(row):
	row = map(str, list(row.values))
	str_row = "".join(row)
	return str_row

def coords(dataset, name):
	row_index = 0
	for i in range(len(dataset)):
		row = dataset.iloc[i]
		row_str = row_stringify(row)
		if name in row_str:
			row_index = i
			break
	col_index = 0
	for j in range(len(dataset.columns)):
		col = dataset.iloc[row_index, j]
		if name in str(col):
			col_index = j
			break
	
	return np.array([row_index, col_index], dtype=np.int64)

In [14]:
coords(
	dataset=dataset[2:],
	name="округ"
)

array([0, 2], dtype=int64)

In [16]:
dataset.iloc[2, 2]

'Центральный федеральный округ'

In [55]:
area_coords = []

for i in range(len(dataset.columns)):
	item = dataset.iloc[2, i]
	item = str(item)
	if len(item) > 5:
		if len(area_coords) > 0:
			area_coords[-1].append([2, i])
		area_coords.append(
			[
				item,
				[2, i]
			]
		)
area_coords[-1].append([2, len(dataset.columns)])

In [56]:
area_coords

[['Центральный федеральный округ', [2, 2], [2, 21]],
 ['Северо-Западный федеральный округ', [2, 21], [2, 33]],
 ['Южный федеральный округ', [2, 33], [2, 42]],
 ['Северо-Кавказский федеральный округ', [2, 42], [2, 50]],
 ['Приволжский федеральный округ', [2, 50], [2, 65]],
 ['Уральский федеральный округ', [2, 65], [2, 72]],
 ['Сибирский федеральный округ', [2, 72], [2, 83]],
 ['Дальневосточный федеральный округ', [2, 83], [2, 95]]]

In [125]:
products_types = """
Гастрономия
Гастрономия
Гастрономия
Гастрономия
Мясо, птица, яйцо
Мясо, птица, яйцо
Гастрономия
Гастрономия
Гастрономия
Гастрономия
Детское питание
Детское питание
Гастрономия
Гастрономия
Мясо, птица, яйцо
Мясо, птица, яйцо
Мясо, птица, яйцо
Мясо, птица, яйцо
Мясо, птица, яйцо
Мясо, птица, яйцо
Гастрономия
Гастрономия
Детское питание
Детское питание
Детское питание
Детское питание
Мясо, птица, яйцо
Мясо, птица, яйцо
Бакалея
Бакалея
Сладкая выпечка
Сладкая выпечка
Шоколад и сладости
Шоколад и сладости
Бакалея
Бакалея
Бакалея
Бакалея
Кулинария
Кулинария
Кулинария
Кулинария
Кулинария
Кулинария
Бакалея
Бакалея
Гастрономия
Гастрономия
Гастрономия
Гастрономия
Бакалея
Бакалея
Бакалея
Бакалея
Бакалея
Бакалея
Бакалея
Бакалея
Бакалея
Бакалея
Овощи/фрукты
Овощи/фрукты
Овощи/фрукты
Овощи/фрукты
Овощи/фрукты
Овощи/фрукты
Овощи/фрукты
Овощи/фрукты
Овощи/фрукты
Овощи/фрукты
Овощи/фрукты
Овощи/фрукты
Овощи/фрукты
Овощи/фрукты
Овощи/фрукты
Овощи/фрукты
Овощи/фрукты
Овощи/фрукты
Алкогольная продукция
Алкогольная продукция
Детское питание
Детское питание
Услуги
Услуги
Рыба и морепродукты
Рыба и морепродукты
Гастрономия
Гастрономия
Бакалея
Бакалея
""".split("\n")

products_types = [item for item in products_types if len(item) > 0]
products_types = [item for i, item in enumerate(products_types) if i % 2 == 0]
products_types

['Гастрономия',
 'Гастрономия',
 'Мясо, птица, яйцо',
 'Гастрономия',
 'Гастрономия',
 'Детское питание',
 'Гастрономия',
 'Мясо, птица, яйцо',
 'Мясо, птица, яйцо',
 'Мясо, птица, яйцо',
 'Гастрономия',
 'Детское питание',
 'Детское питание',
 'Мясо, птица, яйцо',
 'Бакалея',
 'Сладкая выпечка',
 'Шоколад и сладости',
 'Бакалея',
 'Бакалея',
 'Кулинария',
 'Кулинария',
 'Кулинария',
 'Бакалея',
 'Гастрономия',
 'Гастрономия',
 'Бакалея',
 'Бакалея',
 'Бакалея',
 'Бакалея',
 'Бакалея',
 'Овощи/фрукты',
 'Овощи/фрукты',
 'Овощи/фрукты',
 'Овощи/фрукты',
 'Овощи/фрукты',
 'Овощи/фрукты',
 'Овощи/фрукты',
 'Овощи/фрукты',
 'Овощи/фрукты',
 'Алкогольная продукция',
 'Детское питание',
 'Услуги',
 'Рыба и морепродукты',
 'Гастрономия',
 'Бакалея']

In [179]:
new_dataset_columns = [
	"Дата",
	"Страна",
	"Наименование округа",
	"Наименование субъекта",
	"Тип агрегации",
	"Категория товара или услуги",
	"Наименование товара",
	"Средняя цена",
	"Позиция в рейтинге"
]

flat_dataset = {name: [] for name in new_dataset_columns}

for i in range(len(area_coords)):
	start_coords = area_coords[i]
	start_y, start_x = start_coords[1]
	end_y, end_x = start_coords[2]

	subject_name = dataset.iloc[start_y, start_x]
	for col in range(start_x, end_x):
		area_prices = []
		for j in range(7, len(dataset)-1):
			product_name = dataset.iloc[j, 0]
			area_name = dataset.iloc[3, col]
			avg_price = dataset.iloc[j, col]
			date = dataset.iloc[6, col]
			products_type = products_types[j-7]
			flat_dataset["Дата"].append(date)
			flat_dataset["Страна"].append("Российская Федерация")
			flat_dataset["Наименование округа"].append(subject_name)
			flat_dataset["Наименование субъекта"].append(area_name)
			flat_dataset["Тип агрегации"].append("")
			flat_dataset["Категория товара или услуги"].append(products_type)
			flat_dataset["Наименование товара"].append(product_name)
			flat_dataset["Средняя цена"].append(avg_price)
			flat_dataset["Позиция в рейтинге"].append("")
			area_prices.append(avg_price)
		area_prices.sort()
		for k in range(len(area_prices)):
			avg_price = flat_dataset["Средняя цена"][-(k+1)]
			position = area_prices.index(avg_price) + 1
			flat_dataset["Позиция в рейтинге"][-(k+1)] = position

area_prices = []
for j in range(7, len(dataset)-1):
	product_name = dataset.iloc[j, 0]
	avg_price = dataset.iloc[j, 1]
	date = dataset.iloc[6, 1]
	products_type = products_types[j-7]
	flat_dataset["Дата"].append(date)
	flat_dataset["Страна"].append("Российская Федерация")
	flat_dataset["Наименование округа"].append("")
	flat_dataset["Наименование субъекта"].append("")
	flat_dataset["Тип агрегации"].append("")
	flat_dataset["Категория товара или услуги"].append(products_type)
	flat_dataset["Наименование товара"].append(product_name)
	flat_dataset["Средняя цена"].append(avg_price)
	flat_dataset["Позиция в рейтинге"].append("")
	area_prices.append(avg_price)

area_prices.sort()
for k in range(len(area_prices)):
	avg_price = flat_dataset["Средняя цена"][-(k+1)]
	position = area_prices.index(avg_price) + 1
	flat_dataset["Позиция в рейтинге"][-(k+1)] = position

45
45
45
45
45
45
45
45
45
45
45
45
45
45
45
45
45
45
45
45
45
45
45
45
45
45
45
45
45
45
45
45
45
45
45
45
45
45
45
45
45
45
45
45
45
45
45
45
45
45
45
45
45
45
45
45
45
45
45
45
45
45
45
45
45
45
45
45
45
45
45
45
45
45
45
45
45
45
45
45
45
45
45
45
45
45
45
45
45
45
45
45
45

In [181]:
[1, 2, 3][-2]

2

In [89]:
# pd.DataFrame(data=flat_dataset).to_csv("./test.csv")

In [176]:
processed_dataset = pd.DataFrame(data=flat_dataset)

In [177]:
only_subject = (processed_dataset['Наименование субъекта'] == '\xa0') & \
	(processed_dataset['Наименование округа'] != '\xa0')


only_country = (processed_dataset['Наименование субъекта'] == '') & \
	(processed_dataset['Наименование округа'] == '')

processed_dataset.loc[only_country, 'Тип агрегации'] = "Общее значение по РФ"
processed_dataset.loc[only_subject, 'Тип агрегации'] = "Общее значение по округу"
processed_dataset.loc[~(only_country | only_subject), 'Тип агрегации'] = "Общее значение по региону"
processed_dataset.head(3)

,Дата,Страна,Наименование округа,Наименование субъекта,Тип агрегации,Категория товара или услуги,Наименование товара,Средняя цена,Позиция в рейтинге
0,08.07.2022,Российская Федерация,Центральный федеральный округ,,Общее значение по округу,Гастрономия,"Маргарин, кг",266.12,26
1,08.07.2022,Российская Федерация,Центральный федеральный округ,,Общее значение по округу,Гастрономия,"Сметана, кг",307.03,28
2,08.07.2022,Российская Федерация,Центральный федеральный округ,,Общее значение по округу,"Мясо, птица, яйцо","Говядина (кроме бескостного мяса), кг",552.69,36

In [178]:
processed_dataset.to_excel("./test.xlsx", index=False, encoding='utf-8')